const prompt = require('prompt-sync')();
console.log("=== Adição e Multiplicação de Quatro Números Inteiros ===");
let num1 = Number(prompt("Digite o primeiro número inteiro: "));
let num2 = Number(prompt("Digite o segundo número inteiro: "));
let num3 = Number(prompt("Digite o terceiro número inteiro: "));
let num4 = Number(prompt("Digite o quarto número inteiro: "));
let soma = num1 + num2 + num3 + num4;
let multiplicacao = num1 * num2 * num3 * num4;
let s1=num1 + num2;
let s2=num1 + num3;
let s3=num1 + num4;
let s4=num2 + num3;
let s5=num2 + num4;
let s6=num3 + num4;
let m1=num1 * num2;
let m2=num1 * num3;
let m3=num1 * num4;
let m4=num2 * num3;
let m5=num2 * num4;
let m6=num3 * num4;
console.log(`A soma dos quatro números é: ${num1}+${num2} = ${s1}, ${num1}+${num3} = ${s2}, ${num1}+${num4} = ${s3}, ${num2}+${num3} = ${s4}, ${num2}+${num4} = ${s5}, ${num3}+${num4} = ${s6}.`);
console.log(`A multiplicação dos quatro números é: ${num1}*${num2} = ${m1}, ${num1}*${num3} = ${m2}, ${num1}*${num4} = ${m3}, ${num2}*${num3} = ${m4}, ${num2}*${num4} = ${m5}, ${num3}*${num4} = ${m6}.`);             