const prompt = require('prompt-sync')();
console.log("=== Cálculo do Produto e da Soma de Quatro Números Inteiros ===");
let n1 = Number(prompt("Digite o primeiro número inteiro: "));
let n2= Number(prompt("Digite o segundo número inteiro: "));
let n3= Number(prompt("Digite o terceiro número inteiro: "));
let n4= Number(prompt("Digite o quarto número inteiro: "));
let soma = n2 + n4;
let produto = n1 * n3;
console.log(`Soma dos Números: ${soma}`);
console.log(`Produto dos Números: ${produto}`);